name: regression
on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install lua deps
      run: sudo apt update && sudo apt install -y luarocks make && sudo luarocks install luacheck

    - name: Run tests
      run: make lua-lint

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.43
        args: --timeout=5m

    - name: Run tests
      run: make test
